### ISSUE TITLE
Find suitable replacement for actuators

### ISSUE THREAD

**Issue by Pepetruen0** [poppy-project/poppy-humanoid#36]
At $9k, this project is not approachable for hobbyists. I just found this project and was thinking of building one until I saw the BOM cost. Will check back in a couple of years.

**Comment by SX-GitHub** [comment]
This robot is not designed to use toy servos. Robotis servos dominant this sector and all colleges and labs are using them. I found Kondo servos are superior in specs and cost, but they are not drop-in replacements and difficult to find outside of Japan.

**Comment by vkarpuram** [comment]
What about the Lynxmotion Smart Servo: https://www.robotshop.com/en/lynxmotion-smart-servo-lss-high-torque-ht1.html

**Comment by bevinhex** [comment]
should be able to replace with cheaper server with equal torque, I suppose you could use small PIC/AVR micro controllers to output pwm to drive one serve then use i2c to daisy-chain them, thus things like current sensing can be done out of servo, I'm not too sure yet, but since nobody needs all those super-duper sensing/configurations provided, depending on your need, should be fine.
cheap 60kg servo is 45$, 20kg servo 17$, only problem is you also need to touch CAD to adapt things to it.
most important question is what sensor or functionality do we need to do what, look at this guy https://ai2001.ifdef.jp/, the servos he is using seems pretty ordinary, yet it can drag heavy objects and adapt to it

**Comment by gl0p** [comment]
Ive always been interested in making my own little robot and this year i am attempting to design my own, im using the 50$ 60 kg servos, buying two at a time as i go. Just starting off using raspi picos to get it going. Id like to make something cheap enough for people to take interest in. Kind of a bare bones project i guess, something scaleable for different size actuators... we will see.

**Comment by ymollard** [comment]
Closing old issues. Please use the forum for anything that is not a bug.
The forum has several threads about using cheaper motors, e.g. https://poppy.discourse.group/t/is-it-possible-to-replace-robotis-actuators-by-cheaper-ones/128
