### ISSUE TITLE
Is Poppy still alive?

### ISSUE THREAD

**Issue by jiapei100** [poppy-project/poppy-humanoid#43]
Hi, I tried to register [Poppy Forum](https://poppy.discourse.group/), but got the following **ERROR** message:

`Sorry, there was an error authorizing your account. Please try again.`

Just wondering where to print this poppy? Any recommendations?

**Comment by ymollard** [comment]
Hi,

Can you try again registering on the forum a bit later in case it was a punctual issue? The forum seems running as usual. If it still shows the same message, your IP might have been banned by mistake, send it to me at `dev _at_ poppy-station.org`.

Local fablabs are usually the right place for 3D printing, search the [fablab map](https://www.fablabs.io/labs/map) to find one, but make sure that they have a sintering machine, since FDM printing is less convenient for this kind of parts (but some people did it with FDM anyway). Otherwise you can use a service provider, e.g. in Europe [Axis](https://www.axishello.com/en/), [Sculteo](https://www.sculpteo.com/en/) and many other... Otherwise you can buy a [complete kit including 3D printed parts](https://www.generationrobots.com/en/279-poppy-opensource-robotics-platform) that would be ready to assemble.

I'm closing this, please try again to register to the forum if you still need help about the assembly of the robot.
